<?php
/**
 * @var $block \LeSite\CustomBar\Block
 */
?>
<?php if ($block->isModuleEnabled()): ?>


<div class="top-container">
    
    <div class="lesite-custom-section" data-bind="scope: 'section'">
        <!-- ko if: customsection().customerGroup  -->
        <span class="logged-in"
                data-bind="text: new String('<?= $block->escapeHtml(__('Welcome back, your customer group is: %1', '%1')) ?>').replace('%1', customsection().customerGroup)">
        </span>
        <!-- /ko -->
        <!-- ko ifnot: customsection().customerGroup  -->
        <span class="not-logged-in"
                data-bind='html:"<?= $block->escapeHtml(__("Please <a href='%1'>login</a> to know your client group", $block->getUrl('customer/account/login'))) ?>"'>
        </span>
        <!-- /ko -->
    </div>

</div>


<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "section": {
                        "component": "LeSite_CustomBar/js/customsection"
                    }
                }
            }
        }
    }
</script>

<?php endif; ?>