<?php
/**
 * @var Magento\Framework\View\Element\Template $block
 */
?>
<!-- can be CMS Block Admin -->
<!-- <?//echo $block->getLayout()->createBlock(Magento\Cms\Block\Block::class)->setBlockId('huincha-top')->toHtml() ?> -->

<div class="phone-bar" id="phone-bar">
    TALK TO AN EXPERT    <a href="tel: 1-877-244-5650">
        <i class="fas fa-phone-alt"></i>
        1-877-244-5650
    </a>
</div>
